name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v4
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
    - run: npm run prod
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ftpupload.net
        username: epiz_27417802
        password: ${{ secrets.FTP_PASSWORD }}
